// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpecHub.Api.Data;

#nullable disable

namespace SpecHub.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922163346_DocumentAndModule")]
    partial class DocumentAndModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocumentModule", b =>
                {
                    b.Property<Guid>("ModulesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("DocumentVersion")
                        .HasColumnType("integer");

                    b.HasKey("ModulesId", "DocumentId", "DocumentVersion");

                    b.HasIndex("DocumentId", "DocumentVersion");

                    b.ToTable("DocumentModules", (string)null);
                });

            modelBuilder.Entity("SpecHub.Api.Documents.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("created_by");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("last_modified");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "Version");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("SpecHub.Api.Modules.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("Comments")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("Owners")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Components", "SpecHub.Api.Modules.Module.Components#List<Component>", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Capacity");

                            b1
                                .ToJson("Components")
                                .HasColumnType("jsonb");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Parameters", "SpecHub.Api.Modules.Module.Parameters#ModuleParameters", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("CanCopy")
                                .HasJsonPropertyName("can_copy");

                            b1.Property<string>("Color")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("Margin")
                                .IsRequired();

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Frame", "SpecHub.Api.Modules.Module.Parameters#ModuleParameters.Frame#ModuleFrame", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Color")
                                        .IsRequired();

                                    b2.Property<string>("Rounded")
                                        .IsRequired();

                                    b2.Property<int>("Type");

                                    b2.Property<bool>("Visible");

                                    b2.Property<string>("Width")
                                        .IsRequired();
                                });

                            b1
                                .ToJson("Parameters")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("SpecHub.Api.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DocumentModule", b =>
                {
                    b.HasOne("SpecHub.Api.Modules.Module", null)
                        .WithMany()
                        .HasForeignKey("ModulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpecHub.Api.Documents.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId", "DocumentVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
