import type { Uuid } from '../../api/documentTypes';
import type {
  ComponentKey,
  ComponentParamsPatch,
  DocumentMeta,
  DocumentMetaPatch,
  EditorComponent,
  EditorModule,
  ModuleDraftPatch,
} from './types';

/**
 * Reducer actions. Ids/keys are generated by the caller (store layer),
 * so the reducer stays pure and deterministic.
 */
export type EditorAction =
  | { type: 'loadDocument'; meta: DocumentMeta; modules: EditorModule[] }
  | { type: 'addModule'; module: EditorModule }
  | { type: 'removeModule'; moduleId: Uuid }
  | { type: 'moveModule'; moduleId: Uuid; toIndex: number }
  | { type: 'selectModule'; moduleId: Uuid | null }
  | { type: 'openModuleSettings'; moduleId: Uuid }
  | { type: 'openComponentSettings'; moduleId: Uuid; key: ComponentKey }
  | { type: 'closeInspector' }
  | { type: 'updateMeta'; patch: DocumentMetaPatch }
  | { type: 'updateModuleDraft'; moduleId: Uuid; patch: ModuleDraftPatch }
  | { type: 'commitModule'; moduleId: Uuid }
  | { type: 'revertModule'; moduleId: Uuid }
  | { type: 'addComponent'; moduleId: Uuid; component: EditorComponent; index?: number }
  | { type: 'moveComponent'; moduleId: Uuid; key: ComponentKey; toIndex: number }
  | { type: 'updateComponent'; moduleId: Uuid; key: ComponentKey; params: ComponentParamsPatch }
  | { type: 'removeComponent'; moduleId: Uuid; key: ComponentKey }
  | { type: 'resetDirty' };
